export const ADD_TO_CART = 'ADD_TO_CART'
export const ADJUST_ITEM_QTY = 'ADJUST_ITEM_QTY'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS'
export const SAVE_ORDER_FAIL = 'SAVE_ORDER_FAIL'
export const REMOVE_ALL_FROM_CART= 'REMOVE_ALL_FROM_CART'


export const GET_ORDER= "GET_ORDER"
export const POST_ORDER = "ADD_ORDER"

export const DELETE_ORDER = "DELETE_ORDER" 
export const PUT_ORDER = "UPDATE_ORDER" 



export const GET_ORDER_DETAILS_RESET ="GET_ORDER_DETAILS_RESET"

export const GET_ORDER_DETAILS_FAIL="GET_ORDER_DETAILS_FAIL"

export const GET_ORDER_DETAILS_REQUEST="GET_ORDER_DETAILS_REQUEST"
export const GET_ORDER_DETAILS_SUCCESS="GET_ORDER_DETAILS_SUCCESS"